Feature/26 Group photos by date
atereshkov/photomap pull request #48
Opened 2021-05-25 16:34 UTC by jurikmeh

2021-05-25 18:18 UTC, jurikmeh commented on PhotoMap/Core/DI/DIContainer.swift
> +        container.register(FirebaseServiceType.self) { _ in FirebaseService() }
`container.register(FirestoreServiceType.self) { _ in FirestoreService() }`

2021-05-25 18:20 UTC, jurikmeh commented on PhotoMap/Service/FirebaseService/FirebaseServiceType.swift
> +protocol FirebaseServiceType {
`FirestoreServiceType`

2021-05-25 19:20 UTC, atereshkov requested changes

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Service/FirebaseService/FirebaseService.swift
> +enum FirestoreErrorType: Error {
Extract to separated file

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Service/FirebaseService/FirebaseService.swift
> +                        promise(.failure(.custom("no documents")))
Just return empty array. Empty data is not actually means that it's error

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Service/FirebaseService/FirebaseService.swift
> +// swiftlint:disable line_length
Try to avoid using this by splitting to few lines

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Models/Marker.swift
> +        photoURLString = dictionary["photoURL"] as? String ?? "no string-url"
```suggestion
        photoURLString = dictionary["photoURL"] as? String ?? ""
```

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Models/Marker.swift
> +        date = Date(timeIntervalSince1970: TimeInterval(timestamp.seconds + 54_000))
For what + 54_000?

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Models/Marker.swift
> +        category = dictionary["category"] as? String ?? "Default"
```suggestion
        category = dictionary["category"] as? String ?? ""
```

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Models/Marker.swift
> +        location = dictionary["point"] as? (x: Int, y: Int) ?? (0, 0)
Make it optional instead. (0, 0) means some location, it's not empty. So hypothetically it's a location.

Null Island is an imaginary island located at 0°N 0°E in the South Atlantic Ocean. This point is where the Equator meets the Prime Meridian.

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
> +            .sorted { (first, next) -> Bool in first.toMonthAndYearDate > next.toMonthAndYearDate }
```suggestion
            .sorted { $0.toMonthAndYearDate > $1.toMonthAndYearDate }
```

A bit shorter

2021-05-25 19:20 UTC, atereshkov commented on PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
> +                    print(error.description)
Show error to the user

2021-05-26 08:30 UTC, jurikmeh commented on PhotoMap/Features/Timeline/Controllers/TimelineViewController.swift
> +            isLoading ? self?.activityIndicator.startAnimating() : self?.activityIndicator.stopAnimating()
bug: Does not work on inherited indicator

2021-05-26 10:31 UTC, atereshkov requested changes
Build input files cannot be found: '/Users/travis/build/atereshkov/photomap/Marker.swift', '/Users/travis/build/atereshkov/photomap/Models/Category.swift' (in target 'PhotoMap' from project 'PhotoMap')

2021-05-26 11:57 UTC, atereshkov requested changes
Looks good. Time for tests!

2021-05-26 13:49 UTC, merged