Feature 59 load images from storage
atereshkov/photomap pull request #62
Opened 2021-06-14 13:04 UTC by jurikmeh

2021-06-14 13:05 UTC, jurikmeh commented on PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
> +    private let diContainer: DIContainerType
remove this line

2021-06-14 13:06 UTC, jurikmeh commented on PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
> +        self.diContainer = diContainer
remove this line

2021-06-14 17:38 UTC, atereshkov requested changes

2021-06-14 17:38 UTC, atereshkov commented on PhotoMap/Core/Base/Models/Marker.swift
> +    }
Can we actually test it in unit/integration tests?

2021-06-14 17:38 UTC, atereshkov commented on PhotoMap/Features/Timeline/Controllers/MarkerCell.swift
> +        if let url = marker.imageURL, let imageData = try? Data(contentsOf: url), let image = UIImage(data: imageData) {
`marker.imageURL` is local file url or remote resource?

2021-06-14 17:38 UTC, atereshkov commented on PhotoMap/Features/Timeline/Controllers/MarkerCell.swift
> +        if let url = marker.imageURL, let imageData = try? Data(contentsOf: url), let image = UIImage(data: imageData) {
All the logic `if let` etc should not be in cell. Just try to bind data to UI

2021-06-14 17:38 UTC, atereshkov commented on PhotoMap/Service/FirestoreService/FirestoreService.swift
> +                    .child(currentUserId+Separator.slash+marker.date.toString+Separator.point+Path.imageType)
This looks strange :)

2021-06-14 17:38 UTC, atereshkov commented on PhotoMap/Service/FirestoreService/FirestoreService.swift
> +                promise(.failure(.custom("can't find image reference in storage")))
Should be at least localized

2021-06-21 07:00 UTC, atereshkov approved these changes

2021-06-21 07:00 UTC, atereshkov commented on PhotoMapTests/ViewModels/TimelineCellViewModelTests.swift
> +    func testIfHavePhotoLoadItFromCacheDocuments() {
```suggestion
    func test_IfImageExists_LoadItFromCacheDocuments() {
```

2021-06-21 07:57 UTC, merged